# Generated by Django 5.2.4 on 2025-08-11 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('All India Counseling - PG Medical', 'All India Counseling - PG Medical'), ('Armed Forces Medical Services - AFMS (through MCC) - PG Medical', 'Armed Forces Medical Services - AFMS (through MCC) - PG Medical'), ('Open States (Private Institute seats available for all candidates)', 'Open States (Private Institute seats available for all candidates)'), ('Andhra Pradesh Government Quota - PG Medical', 'Andhra Pradesh Government Quota - PG Medical'), ('Andhra Pradesh Management Quota - PG Medical', 'Andhra Pradesh Management Quota - PG Medical'), ('Assam - PG Medical', 'Assam - PG Medical'), ('Bihar - PG Medical', 'Bihar - PG Medical'), ('Chandigarh - PG Medical', 'Chandigarh - PG Medical'), ('Chhattisgarh - PG Medical', 'Chhattisgarh - PG Medical'), ('Delhi - PG Medical', 'Delhi - PG Medical'), ('DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)', 'DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)'), ('Goa - PG Medical', 'Goa - PG Medical'), ('Gujarat - PG Medical', 'Gujarat - PG Medical'), ('Haryana - PG Medical', 'Haryana - PG Medical'), ('Himachal Pradesh - PG Medical', 'Himachal Pradesh - PG Medical'), ('Jammu and Kashmir - PG Medical', 'Jammu and Kashmir - PG Medical'), ('Jharkhand - PG Medical', 'Jharkhand - PG Medical'), ('Karnataka - PG Medical', 'Karnataka - PG Medical'), ('Kerala - PG Medical', 'Kerala - PG Medical'), ('Madhya Pradesh - PG Medical', 'Madhya Pradesh - PG Medical'), ('Maharashtra - PG Medical', 'Maharashtra - PG Medical'), ('Manipur-JNIMS - PG Medical', 'Manipur-JNIMS - PG Medical'), ('Manipur-RIMS - PG Medical', 'Manipur-RIMS - PG Medical'), ('NEIGRIHMS - PG Medical', 'NEIGRIHMS - PG Medical'), ('Odisha - PG Medical', 'Odisha - PG Medical'), ('Pondicherry - PG Medical', 'Pondicherry - PG Medical'), ('Punjab - PG Medical', 'Punjab - PG Medical'), ('Rajasthan - PG Medical', 'Rajasthan - PG Medical'), ('Sikkim - PG Medical', 'Sikkim - PG Medical'), ('Tamil Nadu Government Quota - PG Medical', 'Tamil Nadu Government Quota - PG Medical'), ('Tamil Nadu Management Quota - PG Medical', 'Tamil Nadu Management Quota - PG Medical'), ('Telangana Government Quota - PG Medical', 'Telangana Government Quota - PG Medical'), ('Telangana Management Quota - PG Medical', 'Telangana Management Quota - PG Medical'), ('Tripura - PG Medical', 'Tripura - PG Medical'), ('Uttarakhand - PG Medical', 'Uttarakhand - PG Medical'), ('Uttar Pradesh - PG Medical', 'Uttar Pradesh - PG Medical'), ('West Bengal - PG Medical', 'West Bengal - PG Medical')], max_length=200)),
                ('round', models.CharField(blank=True, max_length=100, null=True)),
                ('ai_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=300, null=True)),
                ('course', models.CharField(blank=True, max_length=300, null=True)),
                ('quota', models.CharField(blank=True, max_length=200, null=True)),
                ('quota_category', models.CharField(blank=True, max_length=200, null=True)),
                ('fee', models.CharField(blank=True, max_length=200, null=True)),
                ('stipend_year1', models.CharField(blank=True, max_length=200, null=True)),
                ('bond_years', models.CharField(blank=True, max_length=50, null=True)),
                ('bond_penalty', models.CharField(blank=True, max_length=200, null=True)),
                ('beds', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeStipendBond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('All India Counseling - PG Medical', 'All India Counseling - PG Medical'), ('Armed Forces Medical Services - AFMS (through MCC) - PG Medical', 'Armed Forces Medical Services - AFMS (through MCC) - PG Medical'), ('Open States (Private Institute seats available for all candidates)', 'Open States (Private Institute seats available for all candidates)'), ('Andhra Pradesh Government Quota - PG Medical', 'Andhra Pradesh Government Quota - PG Medical'), ('Andhra Pradesh Management Quota - PG Medical', 'Andhra Pradesh Management Quota - PG Medical'), ('Assam - PG Medical', 'Assam - PG Medical'), ('Bihar - PG Medical', 'Bihar - PG Medical'), ('Chandigarh - PG Medical', 'Chandigarh - PG Medical'), ('Chhattisgarh - PG Medical', 'Chhattisgarh - PG Medical'), ('Delhi - PG Medical', 'Delhi - PG Medical'), ('DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)', 'DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)'), ('Goa - PG Medical', 'Goa - PG Medical'), ('Gujarat - PG Medical', 'Gujarat - PG Medical'), ('Haryana - PG Medical', 'Haryana - PG Medical'), ('Himachal Pradesh - PG Medical', 'Himachal Pradesh - PG Medical'), ('Jammu and Kashmir - PG Medical', 'Jammu and Kashmir - PG Medical'), ('Jharkhand - PG Medical', 'Jharkhand - PG Medical'), ('Karnataka - PG Medical', 'Karnataka - PG Medical'), ('Kerala - PG Medical', 'Kerala - PG Medical'), ('Madhya Pradesh - PG Medical', 'Madhya Pradesh - PG Medical'), ('Maharashtra - PG Medical', 'Maharashtra - PG Medical'), ('Manipur-JNIMS - PG Medical', 'Manipur-JNIMS - PG Medical'), ('Manipur-RIMS - PG Medical', 'Manipur-RIMS - PG Medical'), ('NEIGRIHMS - PG Medical', 'NEIGRIHMS - PG Medical'), ('Odisha - PG Medical', 'Odisha - PG Medical'), ('Pondicherry - PG Medical', 'Pondicherry - PG Medical'), ('Punjab - PG Medical', 'Punjab - PG Medical'), ('Rajasthan - PG Medical', 'Rajasthan - PG Medical'), ('Sikkim - PG Medical', 'Sikkim - PG Medical'), ('Tamil Nadu Government Quota - PG Medical', 'Tamil Nadu Government Quota - PG Medical'), ('Tamil Nadu Management Quota - PG Medical', 'Tamil Nadu Management Quota - PG Medical'), ('Telangana Government Quota - PG Medical', 'Telangana Government Quota - PG Medical'), ('Telangana Management Quota - PG Medical', 'Telangana Management Quota - PG Medical'), ('Tripura - PG Medical', 'Tripura - PG Medical'), ('Uttarakhand - PG Medical', 'Uttarakhand - PG Medical'), ('Uttar Pradesh - PG Medical', 'Uttar Pradesh - PG Medical'), ('West Bengal - PG Medical', 'West Bengal - PG Medical')], max_length=200)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('institute', models.CharField(blank=True, max_length=300, null=True)),
                ('course', models.CharField(blank=True, max_length=300, null=True)),
                ('quota', models.CharField(blank=True, max_length=200, null=True)),
                ('fee', models.CharField(blank=True, max_length=200, null=True)),
                ('stipend_year1', models.CharField(blank=True, max_length=200, null=True)),
                ('bond_years', models.CharField(blank=True, max_length=50, null=True)),
                ('bond_penalty', models.CharField(blank=True, max_length=200, null=True)),
                ('beds', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeatMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('All India Counseling - PG Medical', 'All India Counseling - PG Medical'), ('Armed Forces Medical Services - AFMS (through MCC) - PG Medical', 'Armed Forces Medical Services - AFMS (through MCC) - PG Medical'), ('Open States (Private Institute seats available for all candidates)', 'Open States (Private Institute seats available for all candidates)'), ('Andhra Pradesh Government Quota - PG Medical', 'Andhra Pradesh Government Quota - PG Medical'), ('Andhra Pradesh Management Quota - PG Medical', 'Andhra Pradesh Management Quota - PG Medical'), ('Assam - PG Medical', 'Assam - PG Medical'), ('Bihar - PG Medical', 'Bihar - PG Medical'), ('Chandigarh - PG Medical', 'Chandigarh - PG Medical'), ('Chhattisgarh - PG Medical', 'Chhattisgarh - PG Medical'), ('Delhi - PG Medical', 'Delhi - PG Medical'), ('DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)', 'DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)'), ('Goa - PG Medical', 'Goa - PG Medical'), ('Gujarat - PG Medical', 'Gujarat - PG Medical'), ('Haryana - PG Medical', 'Haryana - PG Medical'), ('Himachal Pradesh - PG Medical', 'Himachal Pradesh - PG Medical'), ('Jammu and Kashmir - PG Medical', 'Jammu and Kashmir - PG Medical'), ('Jharkhand - PG Medical', 'Jharkhand - PG Medical'), ('Karnataka - PG Medical', 'Karnataka - PG Medical'), ('Kerala - PG Medical', 'Kerala - PG Medical'), ('Madhya Pradesh - PG Medical', 'Madhya Pradesh - PG Medical'), ('Maharashtra - PG Medical', 'Maharashtra - PG Medical'), ('Manipur-JNIMS - PG Medical', 'Manipur-JNIMS - PG Medical'), ('Manipur-RIMS - PG Medical', 'Manipur-RIMS - PG Medical'), ('NEIGRIHMS - PG Medical', 'NEIGRIHMS - PG Medical'), ('Odisha - PG Medical', 'Odisha - PG Medical'), ('Pondicherry - PG Medical', 'Pondicherry - PG Medical'), ('Punjab - PG Medical', 'Punjab - PG Medical'), ('Rajasthan - PG Medical', 'Rajasthan - PG Medical'), ('Sikkim - PG Medical', 'Sikkim - PG Medical'), ('Tamil Nadu Government Quota - PG Medical', 'Tamil Nadu Government Quota - PG Medical'), ('Tamil Nadu Management Quota - PG Medical', 'Tamil Nadu Management Quota - PG Medical'), ('Telangana Government Quota - PG Medical', 'Telangana Government Quota - PG Medical'), ('Telangana Management Quota - PG Medical', 'Telangana Management Quota - PG Medical'), ('Tripura - PG Medical', 'Tripura - PG Medical'), ('Uttarakhand - PG Medical', 'Uttarakhand - PG Medical'), ('Uttar Pradesh - PG Medical', 'Uttar Pradesh - PG Medical'), ('West Bengal - PG Medical', 'West Bengal - PG Medical')], max_length=200)),
                ('institute', models.CharField(blank=True, max_length=300, null=True)),
                ('program', models.CharField(blank=True, max_length=300, null=True)),
                ('quota', models.CharField(blank=True, max_length=200, null=True)),
                ('open_seats', models.IntegerField(blank=True, null=True)),
                ('open_pwd', models.IntegerField(blank=True, null=True)),
                ('gen_ews', models.IntegerField(blank=True, null=True)),
                ('gen_ews_pwd', models.IntegerField(blank=True, null=True)),
                ('obc', models.IntegerField(blank=True, null=True)),
                ('obc_pwd', models.IntegerField(blank=True, null=True)),
                ('sc', models.IntegerField(blank=True, null=True)),
                ('sc_pwd', models.IntegerField(blank=True, null=True)),
                ('st', models.IntegerField(blank=True, null=True)),
                ('st_pwd', models.IntegerField(blank=True, null=True)),
                ('total_seats', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='closingrank',
            name='closing_rank',
        ),
        migrations.RemoveField(
            model_name='closingrank',
            name='round',
        ),
        migrations.AddField(
            model_name='closingrank',
            name='beds',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='bond_penalty',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='bond_years',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2023_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2023_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2023_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2023_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2023_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2024_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2024_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2024_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2024_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='cr_2024_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.date(2025, 8, 11)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='closingrank',
            name='fee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='quota',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='quota_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='state',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='stipend_year1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='closingrank',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='closingrank',
            name='category',
            field=models.CharField(choices=[('All India Counseling - PG Medical', 'All India Counseling - PG Medical'), ('Armed Forces Medical Services - AFMS (through MCC) - PG Medical', 'Armed Forces Medical Services - AFMS (through MCC) - PG Medical'), ('Open States (Private Institute seats available for all candidates)', 'Open States (Private Institute seats available for all candidates)'), ('Andhra Pradesh Government Quota - PG Medical', 'Andhra Pradesh Government Quota - PG Medical'), ('Andhra Pradesh Management Quota - PG Medical', 'Andhra Pradesh Management Quota - PG Medical'), ('Assam - PG Medical', 'Assam - PG Medical'), ('Bihar - PG Medical', 'Bihar - PG Medical'), ('Chandigarh - PG Medical', 'Chandigarh - PG Medical'), ('Chhattisgarh - PG Medical', 'Chhattisgarh - PG Medical'), ('Delhi - PG Medical', 'Delhi - PG Medical'), ('DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)', 'DNB Sponsored - PG Medical (Govt or PSU Inservice Candidates)'), ('Goa - PG Medical', 'Goa - PG Medical'), ('Gujarat - PG Medical', 'Gujarat - PG Medical'), ('Haryana - PG Medical', 'Haryana - PG Medical'), ('Himachal Pradesh - PG Medical', 'Himachal Pradesh - PG Medical'), ('Jammu and Kashmir - PG Medical', 'Jammu and Kashmir - PG Medical'), ('Jharkhand - PG Medical', 'Jharkhand - PG Medical'), ('Karnataka - PG Medical', 'Karnataka - PG Medical'), ('Kerala - PG Medical', 'Kerala - PG Medical'), ('Madhya Pradesh - PG Medical', 'Madhya Pradesh - PG Medical'), ('Maharashtra - PG Medical', 'Maharashtra - PG Medical'), ('Manipur-JNIMS - PG Medical', 'Manipur-JNIMS - PG Medical'), ('Manipur-RIMS - PG Medical', 'Manipur-RIMS - PG Medical'), ('NEIGRIHMS - PG Medical', 'NEIGRIHMS - PG Medical'), ('Odisha - PG Medical', 'Odisha - PG Medical'), ('Pondicherry - PG Medical', 'Pondicherry - PG Medical'), ('Punjab - PG Medical', 'Punjab - PG Medical'), ('Rajasthan - PG Medical', 'Rajasthan - PG Medical'), ('Sikkim - PG Medical', 'Sikkim - PG Medical'), ('Tamil Nadu Government Quota - PG Medical', 'Tamil Nadu Government Quota - PG Medical'), ('Tamil Nadu Management Quota - PG Medical', 'Tamil Nadu Management Quota - PG Medical'), ('Telangana Government Quota - PG Medical', 'Telangana Government Quota - PG Medical'), ('Telangana Management Quota - PG Medical', 'Telangana Management Quota - PG Medical'), ('Tripura - PG Medical', 'Tripura - PG Medical'), ('Uttarakhand - PG Medical', 'Uttarakhand - PG Medical'), ('Uttar Pradesh - PG Medical', 'Uttar Pradesh - PG Medical'), ('West Bengal - PG Medical', 'West Bengal - PG Medical')], max_length=200),
        ),
        migrations.AlterField(
            model_name='closingrank',
            name='course',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='closingrank',
            name='institute',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
